### PR TITLE
multiple_commits

### PR DESCRIPTION
**Pull request by peter1000**
To avoid rebasing issues I will push multiple commits to one PR

* renames: genindexfiledir => indexfiledir

* Important: code improvement replaces redundant Vectors in `Entries` -
I missed that this is not needed.

* Doc updates and more `config.md` examples

### CODE REVIEW

**Comment by peter1000** [comment]
This is the last for now: when you merged that this should also close issue #92

**Comment by peter1000** [comment]
**This is the last for now: when you merge** - this should also close issue #92

Uploaded an example: http://peter1000.github.io/Lexicon.jl/api/

NOTE: Sections is probably only useful for bigger documentations and might also depend on what 3rd party tool one uses: if the Sections appear in any navigation menues ect.

Section permalink are `disabled by default` - but the Config defaults might need some looking into at a later point.

**Comment by peter1000** [comment]
hi I uploaded the latest build with all the additional permalink and anchor http://peter1000.github.io/Lexicon.jl/

So in an webforum one can reference for instance the "Internal" Lexicon Section with quite a nice reference link:
http://peter1000.github.io/Lexicon.jl/api/Lexicon/#lexicon__internal

The same works for the objectnames which alwaus prefixes the category they belong to: http://peter1000.github.io/Lexicon.jl/api/Lexicon/#method__filter.1

**Comment by peter1000** [comment]
**Sorry** I don't like how I did the Config options - will streamline it and redo a new clean PR.
No need to discuss this.

**Comment by MichaelHatherly** [comment]
>I don't like how I did the Config options - will streamline it and redo a new clean PR.

Sure, no problem. Also, @peter1000 if I've missed any particular point you'd like answered (in any of the PRs or issues) please do ping me again in them. Thanks.

**Comment by peter1000** [comment]
I think I'm fine for now: slowly I get a bit easier around the code.

Anyway my plan would be like this:

1. add to Docile the signature extraction (this should only be an addition and not change for now the current behavior

2. for a start add to Lexicon an option to use the new signature (but also leave the old one intact so we do not mess up anything untll all is established

3. Do the whole Section part new: I have most of it already done but must adjust it a bit for the new signature part.

4. maybe do with the section also this user option: what do you think about this: https://github.com/MichaelHatherly/Lexicon.jl/issues/8

**Comment by MichaelHatherly** [comment]
> add to Docile the signature extraction

I'd suggest capturing the entire `Expr` on the Docile side and storing it in `:code` field of an entry's metadata. There many be other useful information we could extract at a later date. Then extract the relevant parts on the Lexicon side.

> for a start add to Lexicon an option to use the new signature (but also leave the old one intact so we do not mess up anything untll all is established

Sounds good.

> maybe do with the section also this user option: what do you think about this: #8

Yeah, that would be a nice addition.

**Pull request closed without merging**
