### PR TITLE
relpath is only needed for julia < 0.4-

### PR DESCRIPTION
**Pull request by peter1000**
`relpath` got merged: https://github.com/JuliaLang/julia/pull/10893

### CODE REVIEW

**Comment by peter1000** [comment]
Failed I will check this again with a julia stable version.

**Comment by MichaelHatherly** [comment]
Since `relpath` isn't available in every version of `0.4-` you'll need to make that conditional more specific, such as `0.4-XXXX` where `XXXX` can be calculated using the script in the Compat package, https://github.com/JuliaLang/Compat.jl#developer-tips. (Technically the `findprev` and `findlast` should be as well. I can get that sorted since it was me who suggested using the conditional.)

Perhaps we should move all the "compat"-like things into a separate file, `compat.jl`, to better keep track of compat fixes specific to this package?

**Comment by peter1000** [comment]
> Perhaps we should move all the "compat"-like things into a separate file, compat.jl, to better keep track of compat fixes specific to this package?

Ok I can start this and resend here a PR?

**Comment by MichaelHatherly** [comment]
> Ok I can start this and resend here a PR?

Yeah, that's fine.

**Comment by MichaelHatherly** [comment]
I'm getting:

```
$ compat.sh e3aa57efbc6542efbcc7feac9b1309d628ac6f12
2418
```

for the `find` methods and
```
$ compat.sh 13302e6dd94b188d6a09ec35f7f0291e77ee3686
4393
```

for your `relpath` addition.

**Comment by peter1000** [comment]
just for the future: could you show me shortly the whole process how to get the number - never did it?

**Comment by MichaelHatherly** [comment]
Put the `bash` script found at the bottom of the Compat README into a file

```bash
#! /bin/bash
last_tag=$(git describe --tags --abbrev=0)
git rev-list $1 ^$last_tag | wc -l | sed -e 's/[^[:digit:]]//g'
```

on your path and make it executable using `chmod +x compat.sh`. (This assumes you're on a *nix system, can't help you if it's windows, appologies.)

Search the git commit logs for the specific commit that added the feature. Best to just use the github interface for this I find. This was yours https://github.com/JuliaLang/julia/commit/13302e6dd94b188d6a09ec35f7f0291e77ee3686.

Get the hash associated with the commit. (13302e6dd94b188d6a09ec35f7f0291e77ee3686).

`cd` into the julia repo.

Run

```bash
$ compat.sh 13302e6dd94b188d6a09ec35f7f0291e77ee3686
```

and use the resulting `XXXX` number in the conditional.

```jl
if VERSION >= v"0.4-XXXX"
    # ...
end
```

**Comment by peter1000** [comment]
Thanks

**Comment by peter1000** [comment]
sorry forgot to push here - a new PR #76

**Pull request closed without merging**
