### PR TITLE
added_config_dict

### PR DESCRIPTION
**Pull request by peter1000**
Using Dict for potential increase in configuration settings.

https://github.com/MichaelHatherly/Lexicon.jl/issues/52

### CODE REVIEW

**Comment by peter1000** [comment]
sorry failed

**Comment by MichaelHatherly** [comment]
I've just commented on #52 on a potential `Config` object. (Hadn't seen your PR yet, sorry.) Let me know what you think about that approach.

**Comment by peter1000** [comment]
I was thinking first about using types but was unsure if you want such. Anyway I think it is a nicer approach and also avoids some of the user input validation - I can do it - though not sure if I have time tonight.

**Comment by MichaelHatherly** [comment]
Yeah, sorry about being vague earlier. The `Config` will be a *much* nicer solution than either the current situation or a `Dict`.

No worries about time really, whenever you get a chance. I'm in no hurry.

**Pull request closed without merging**
