### PR TITLE
Implements: Permalink and API-Index for markdown output.

### PR DESCRIPTION
**Pull request by peter1000**
Implements Enhancement #43

* Add optional API-Index for markdown output.
* Add optional Permalink for markdown output.
* Some additional explanatory code comments / documentation.
* Adjusted some documentation for the new API-Index.
* Adjusted tests.

### CODE REVIEW

**Comment by peter1000** [comment]
You will need to rebuild the docs: [Documentation should *only* be build directly on the `master` branch.](https://github.com/MichaelHatherly/Lexicon.jl/commit/4853a3a64d72e4f7e6e9ba63b2f1f6ef7a3e8b07#diff-1657d9d74f07d5170267afb47e5ee793R34)

example will be deleted later: http://peter1000.github.io/Lexicon_Test/api/Lexicon/

**Comment by MichaelHatherly** [comment]
Thanks @peter1000, will need a few days to properly review this &ndash; unfortunately postgrad work must come first. From an initial read through does look good though.

**Comment by peter1000** [comment]
just thought about: I did not include / consider for something like:

```julia
@doc meta(file = "../my/external/file.md") ->
foobar(x) = 2x + 1

file"../docs/methods/f.md"
f(x) = 2x
```

Just tried it but I get an error even without the permalink.... maybe I do something wrong or we broke it with the previous commits.

I downloaded also a prebuild julia v0.3.7 but the same.
```
[userk@evo bin]$ ./julia /home/userk/.julia/v0.3/Lexicon/docs/build.jl
ERROR: key not found: :root
 in getindex at dict.jl:617
 in Entry at /home/userk/.julia/v0.3/Docile/src/types.jl:67
 in setmeta! at /home/userk/.julia/v0.3/Docile/src/types.jl:153
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include! at /home/userk/.julia/v0.3/Docile/src/Docile.jl:68
 in anonymous at /home/userk/.julia/v0.3/Docile/src/Docile.jl:96
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include! at /home/userk/.julia/v0.3/Docile/src/Docile.jl:68
 in anonymous at /home/userk/.julia/v0.3/Docile/src/Docile.jl:96
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
while loading /home/userk/.julia/v0.3/Lexicon/src/render/md.jl, in expression starting on line 3
while loading /home/userk/.julia/v0.3/Lexicon/src/render.jl, in expression starting on line 156
while loading /home/userk/.julia/v0.3/Lexicon/src/Lexicon.jl, in expression starting on line 44
while loading /home/userk/.julia/v0.3/Lexicon/docs/build.jl, in expression starting on line 
```

**Comment by MichaelHatherly** [comment]
I can't recreate that error, is that the whole code snippet?

Just tried adding

```julia
file"../README.md"
Lexicon
```

to the package. REPL and markdown output worked fine.
```

**Comment by peter1000** [comment]
Yes this works... even the index entry seems to be ok.  Highlighted when adding the Readme as above. Seems all ok.

untitled

**Pull request closed without merging**
